title: Cocoon
baseurl: "/cocoon"

markdown: kramdown

tracking_id: #

footer_url: "https://github.com/pro-panda"
footer_text: "Pro-Panda | 2018"

profile-picture: harry.jpg

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
